### PR TITLE
fixed missing methods and imports:

### PR DESCRIPTION
**Pull request by picciama**
1. import pkg_constants via externals.py
2. added missing param_bounds method to norm and beta simulator
3. added missing eta_loc_j to norm and beta simulator

### CODE REVIEW

**Comment by picciama** [comment]
Should fix #95

**Comment by picciama** [comment]
@ilan-gold Please see if this fixes your issues with eta_loc_j and not being able to simulate norm and beta distribution.

**Comment by picciama** [comment]
@ilan-gold did it work? Methods should be correct but I'm not so sure about the param_bounds methods.

**Comment by ilan-gold** [comment]
@picciama sorry, yes, I think I mentioned in my email that I merged this into my branch.  There are still other issues but this did work.

**Pull request merged**
